# Generated by Django 4.2 on 2023-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_iterviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterviews',
            name='recording',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
