# Generated by Django 4.2 on 2023-04-29 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0009_iterviews_recording'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iterviews',
            new_name='Interviews',
        ),
    ]
