# Generated by Django 4.2 on 2023-04-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_iterviews_interviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
